spring:
  application:
    name: "nerinyan-api"

discord:
  webhook:
    startup: "${DISCORD_WEBHOOK_STARTUP:}"
    shutdown: "${DISCORD_WEBHOOK_SHUTDOWN:}"
    info: "${DISCORD_WEBHOOK_INFO:}"
    error: "${DISCORD_WEBHOOK_ERROR:}"

bancho:
  clientId: "${BANCHO_CLIENTID:5}"
  clientSecret: "${BANCHO_CLIENTSECRET:FGc9GAtyHzeQDshWP5Ah7dega8hJACAJpQtw6OXk}"
  scope: "${BANCHO_SCOPE:*}"
  url: "${BANCHO_URL:https://osu.ppy.sh/oauth/token}"
  username: "${BANCHO_USERNAME:}"
  password: "${BANCHO_PASSWORD:}"